version: '3.8'
services:
    prometheus:
      image: prom/prometheus
      restart: unless-stopped
      volumes:
        - "./docker-compose/:/etc/prometheus/:ro"
        - "prometheus_data:/prometheus"
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      labels:
        - server.user=${TRAEFIK_IDENT}
        - "traefik.enable=true"
        - traefik.docker.network=${PROMETHEUS_NAME}_metrics
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.kikkirej.net`)"
        - "traefik.http.routers.prometheus.service=prometheus"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.middlewares=security-chain@file"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      environment:
        - TZ=Europe/Berlin
      networks:
        - metrics
volumes:
    prometheus_data: {}

networks:
    metrics:
        name: ${PROMETHEUS_NAME}_metrics
