# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
  # - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']


  - job_name: 'traefik'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['traefik:8080']
    
  - job_name: 'teamspeak'

    scrape_interval: 15s

    static_configs:
         - targets: ['ts3-exporter-prometheus:9189']
    
  - job_name: 'grafana'

    static_configs:
         - targets: ['grafana:3000']

  - job_name: 'grafana-fitx'

    static_configs:
         - targets: ['grafana-fitx:3000']
    
  - job_name: 'jaeger-agent'

    static_configs:
         - targets: ['jaeger-agent:14271']

  - job_name: 'jaeger-collector'

    static_configs:
         - targets: ['jaeger-collector:14269']

  - job_name: 'jaeger-query'

    static_configs:
         - targets: ['jaeger-query:16687']
  
  - job_name: 'nextcloud'

    static_configs:
          - targets: ['cloud-prometheus-exporter:9205']

